#!/usr/bin/env python3

import sys

def factorize(n):
    factors = []
    i = 2
    while i * i <= n:
        if n % i:
            i += 1
        else:
            n //= i
            factors.append(i)
    if n > 1:
        factors.append(n)
    return factors

def main(filename):
    with open(filename, 'r') as file:
        for line in file:
            n = int(line.strip())
            factorization = factorize(n)
            print(f"{n}={'*'.join(map(str, factorization))}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        print("where <file> is a file containing natural numbers to factor.")
        sys.exit(1)
    filename = sys.argv[1]
    main(filename)
